apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/hafa39/catalog-service-v3/k8s?ref=main
 #Uses the manifests in your Catalog Service repo on GitHub as the base for further customizations

#patchesStrategicMerge:
#  - patch-env.yml

#because patchesStrategicMerge deprecated use this
patches:
  - path: patch-env.yml


configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: catalog-config

images:
  - name: catalog-service
    newName: ghcr.io/hafa39/catalog-service-v3
    newTag: latest

replicas:
  - name: catalog-service
    count: 2
